include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: false
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    unnecessary_async: true
    unnecessary_const: true
    unnecessary_final: true
    unnecessary_ignore: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    use_enums: true
    use_rethrow_when_possible: true
    annotate_overrides: true
    constant_identifier_names: false