name: twoaxis_finance
description: "An application to manage your finances"
publish_to: 'none'

version: 1.4.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.20.1
  url_launcher: ^6.3.1
  flutter_bloc: ^9.0.0
  fl_chart: ^0.70.2
  lottie: ^3.3.1
  google_sign_in: ^6.3.0
  flutter_native_splash: ^2.4.7
  equatable: ^2.0.8
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/animations/

flutter_native_splash:
  color: "#121212"
  image: "assets/images/splash_icon.png"
  branding_bottom_padding: 32
  branding: "assets/images/branding.png"

  android_12:
    color: "#121212"
    image: "assets/images/splash_icon.png"
    branding: "assets/images/branding.png"
    branding_bottom_padding: 32
