export const currencies: Record<string, string> = {
  'USD': 'United States Dollar', 'EUR': 'Euro', 'EGP': 'Egyptian Pound',
  'GBP': 'British Pound', 'JPY': 'Japanese Yen', 'CNY': 'Chinese Yuan',
  'INR': 'Indian Rupee', 'SAR': 'Saudi Riyal', 'AED': 'UAE Dirham',
  'CAD': 'Canadian Dollar', 'AUD': 'Australian Dollar', 'CHF': 'Swiss Franc',
  'ZAR': 'South African Rand', 'KWD': 'Kuwaiti Dinar', 'QAR': 'Qatari Riyal',
  'TRY': 'Turkish Lira', 'NOK': 'Norwegian Krone', 'SEK': 'Swedish Krona',
  'DKK': 'Danish Krone', 'RUB': 'Russian Ruble', 'MXN': 'Mexican Peso',
  'BRL': 'Brazilian Real', 'ARS': 'Argentine Peso', 'PKR': 'Pakistani Rupee',
  'THB': 'Thai Baht', 'IDR': 'Indonesian Rupiah', 'KRW': 'South Korean Won',
  'SGD': 'Singapore Dollar', 'MYR': 'Malaysian Ringgit', 'NGN': 'Nigerian Naira',
  'TWD': 'Taiwan Dollar', 'VND': 'Vietnamese Dong', 'PLN': 'Polish Zloty',
  'CZK': 'Czech Koruna', 'HUF': 'Hungarian Forint', 'ILS': 'Israeli Shekel',
  'RON': 'Romanian Leu', 'UAH': 'Ukrainian Hryvnia', 'DZD': 'Algerian Dinar',
  'MAD': 'Moroccan Dirham', 'JOD': 'Jordanian Dinar', 'LBP': 'Lebanese Pound',
  'TND': 'Tunisian Dinar', 'OMR': 'Omani Rial', 'BHD': 'Bahraini Dinar',
};
