name: Flutter

on: ["pull_request"]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.5
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Analyze Code
        run: flutter analyze
        working-directory: mobile

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.5
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > mobile/android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=keystore.jks" > mobile/android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> mobile/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> mobile/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> mobile/android/key.properties

      - name: Build APK
        run: flutter build apk --release
        working-directory: mobile

  build-aab:
    name: Build App Bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.5
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > mobile/android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=keystore.jks" > mobile/android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> mobile/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> mobile/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> mobile/android/key.properties

      - name: Build App Bundle
        run: flutter build appbundle
        working-directory: mobile
